# Tomcat
server:
  port: 8080

#spring
spring:
  datasource:
    #???????????
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:identifier.sqlite
    username:
    password:
  # ?????????
  web:
    resources:
      static-locations: classpath:/static/

#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml

